### ISSUE TITLE
missing conditional_entropy

### ISSUE THREAD

**Issue by ChenS676** [amazon-science/Network-Usable-Info-Framework#5]
Dear Mr. Zhang 

Thanks for your excellent work and update. 

I've recently encountered an issue while working with the project. Specifically, I couldn't locate the `conditional_entropy` function within the `models/nui.py` file. It seems to be missing or misplaced. Could you please provide guidance on where I can find it or any alternative solution?

Additionally, I've encountered difficulties when attempting to compile the C++ code. It seems there's an error during compilation. **I'm wondering if there are any additional configurations required for the C++ compiler.** It's worth noting that I haven't previously developed graph algorithms in C++, so any assistance or clarification you can provide would be greatly appreciated.

Thank you for your attention to this matter.

Best regards,
cshao

**Comment by zhjwy9343** [comment]
Thanks for reach out to us. @mengchillee can help with that.

**Comment by mengchillee** [comment]
Hi Chen,

Regarding the first issue about `conditional_entropy`, it has been resolved in #6.
Thank you for pointing it out!

Regarding the second issue about compilation error, could you please provide the error you encountered?

**Comment by zhjwy9343** [comment]
Since all issues have been solved, I will close this issue. Thanks.
